### model
model_name_or_path: <model_path>
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: lora
lora_rank: 16
lora_target: all

### dataset
dataset: resistance_evaluation_training_exp_fold3
template: llama3
cutoff_len: 8192
max_samples: 10000
preprocessing_num_workers: 16
dataloader_num_workers: 4

### output
output_dir: <save path>
logging_steps: 10
save_steps: 10
plot_loss: true
overwrite_output_dir: true
save_only_model: false
report_to: swanlab  # choices: [none, wandb, tensorboard, swanlab, mlflow]
save_total_limit: 1

### train
per_device_train_batch_size: 2
gradient_accumulation_steps: 4
learning_rate: 1.0e-4
num_train_epochs: 5.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
resume_from_checkpoint: null

### eval
# eval_dataset: alpaca_en_demo
# val_size: 0.1
# per_device_eval_batch_size: 1
# eval_strategy: steps
# eval_steps: 500

eval_dataset: resistance_evaluation_valid_exp_fold3
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 10
load_best_model_at_end: true
metric_for_best_model: eval_loss
greater_is_better: false

# val_size: 0.1

### swanlab
use_swanlab: true
swanlab_project: resistance_measurement
swanlab_run_name: training_lora_rank16_exp_fold3


# CUDA_VISIBLE_DEVICES=0,1,2,3 DISABLE_VERSION_CHECK=1 nohup llamafactory-cli train examples/train_lora/llama3_lora_sft.yaml >llama3_lora_sft_training_exp_fold3_rank16_lr1e4.log 2>&1 &

